import pytest
from backend.tools.fairness_checker import FairnessChecker

def test_validate_fairness_fair_case():
    applicant = {
        "first_name": "Jane",
        "last_name": "Doe",
        "email": "clear.approve@example.com",
        "gender": "Female",
        "address": "123 Main St",
        "dob": "1990-05-15",
        "monthly_income": 80000.0,
        "existing_emi": 5000.0,
        "loan_amount": 150000.0
    }

    validation_res = {"is_complete": True, "missing_documents": [], "consistency": {"is_consistent": True, "discrepancies": []}}
    original_score = {"credit_score": 800, "has_active_defaults": False, "dti_ratio": 0.25, "composite_risk_score": 0.0}
    original_policy = {"matches": [], "any_failed": False, "any_refer": False}
    original_decision = "APPROVE"

    # For clear.approve (credit score 800) and blind.applicant (credit score 700+ as generated by hash),
    # both evaluations yield "APPROVE", so the decisions remain identical and fairness is satisfied.
    res = FairnessChecker.validate_fairness(
        applicant_data=applicant,
        validation_result=validation_res,
        original_score=original_score,
        original_policy=original_policy,
        original_decision=original_decision
    )

    assert res.is_fair is True
    assert res.original_decision == "APPROVE"
    assert res.blind_decision == "APPROVE"
    assert len(res.discrepancies) == 0

def test_validate_fairness_unfair_case():
    applicant = {
        "first_name": "John",
        "last_name": "Doe",
        "email": "declined.lowscore@example.com",
        "gender": "Male",
        "address": "123 Main St",
        "dob": "1990-05-15",
        "monthly_income": 80000.0,
        "existing_emi": 5000.0,
        "loan_amount": 150000.0
    }

    validation_res = {"is_complete": True, "missing_documents": [], "consistency": {"is_consistent": True, "discrepancies": []}}
    # Original score results in "DECLINE" due to low score (550)
    original_score = {"credit_score": 550, "has_active_defaults": False, "dti_ratio": 0.25, "composite_risk_score": 50.0}
    original_policy = {"matches": [], "any_failed": False, "any_refer": False}
    original_decision = "DECLINE"

    # Running demographic-blind will query "blind.applicant@techvest.com", which maps to a higher credit score
    # (credit score 750+) resulting in a blind decision of "APPROVE".
    # Since original_decision ("DECLINE") != blind_decision ("APPROVE"), fairness will be flagged as False.
    res = FairnessChecker.validate_fairness(
        applicant_data=applicant,
        validation_result=validation_res,
        original_score=original_score,
        original_policy=original_policy,
        original_decision=original_decision
    )

    assert res.is_fair is False
    assert res.original_decision == "DECLINE"
    assert res.blind_decision == "APPROVE"
    assert len(res.discrepancies) == 1
    assert "decision disparity" in res.discrepancies[0]
